### ISSUE TITLE
Rand

### ISSUE THREAD

**Issue by janhohenheim** [EmiOnGit/warblersneeds#2]
I've seen that you're looking for a better random function to use in your shader. I can recommend this GDC talk for inspiration: [Noise-Based RNG](https://www.youtube.com/watch?v=LWFzPP8ZbdU) 🙂

**Comment by EmiOnGit** [comment]
Hey jan,
that's a really interesting talk, thank you for sharing! :)
In fact, I just noticed that I'd need a noise instead of random numbers.
I will definitely try optimizing the shader part today or tomorrow

**Comment by EmiOnGit** [comment]
There we go! :)
Do you care to take a look? 
Anyways, thank you for opening the ticket :+1:

**Comment by janhohenheim** [comment]
Looks great now 🥇
